INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME) VALUES (1, 'Harshal Shimpi');
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME) VALUES (2, 'Tejas Patil');

INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (1, 120, '2026-01-10', 1);
INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (2, 75, '2026-01-15', 1);

INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (3, 200, '2026-02-05', 1);
INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (4, 90, '2026-02-20', 2);

INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (5, 130, '2026-03-01', 1);
INSERT INTO CUSTOMER_TXN (TXN_ID, TXN_AMOUNT, TXN_DATE, CUSTOMER_ID)
VALUES (6, 45, '2026-03-03', 2);